/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AlunoAgendaRouteImport } from './routes/aluno.agenda'
import { Route as AlunoAvaliacoesRouteImport } from './routes/aluno.avaliacoes'
import { Route as AlunoAvatarRouteImport } from './routes/aluno.avatar'
import { Route as AlunoCoachRouteImport } from './routes/aluno.coach'
import { Route as AlunoEvolucaoRouteImport } from './routes/aluno.evolucao'
import { Route as AlunoFinanceiroRouteImport } from './routes/aluno.financeiro'
import { Route as AlunoFotosRouteImport } from './routes/aluno.fotos'
import { Route as AlunoMateriaisRouteImport } from './routes/aluno.materiais'
import { Route as AlunoMensagensRouteImport } from './routes/aluno.mensagens'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AlunoTimelineRouteImport } from './routes/aluno.timeline'
import { Route as AlunoTreinosRouteImport } from './routes/aluno.treinos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAgendaRoute = AlunoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAvaliacoesRoute = AlunoAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAvatarRoute = AlunoAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoCoachRoute = AlunoCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoEvolucaoRoute = AlunoEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoFinanceiroRoute = AlunoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoFotosRoute = AlunoFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoMateriaisRoute = AlunoMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoMensagensRoute = AlunoMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoTimelineRoute = AlunoTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoTreinosRoute = AlunoTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AlunoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/avaliacoes': typeof AlunoAvaliacoesRoute
  '/aluno/avatar': typeof AlunoAvatarRoute
  '/aluno/coach': typeof AlunoCoachRoute
  '/aluno/evolucao': typeof AlunoEvolucaoRoute
  '/aluno/financeiro': typeof AlunoFinanceiroRoute
  '/aluno/fotos': typeof AlunoFotosRoute
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/mensagens': typeof AlunoMensagensRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/timeline': typeof AlunoTimelineRoute
  '/aluno/treinos': typeof AlunoTreinosRoute
  '/aluno/': typeof AlunoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/avaliacoes': typeof AlunoAvaliacoesRoute
  '/aluno/avatar': typeof AlunoAvatarRoute
  '/aluno/coach': typeof AlunoCoachRoute
  '/aluno/evolucao': typeof AlunoEvolucaoRoute
  '/aluno/financeiro': typeof AlunoFinanceiroRoute
  '/aluno/fotos': typeof AlunoFotosRoute
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/mensagens': typeof AlunoMensagensRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/timeline': typeof AlunoTimelineRoute
  '/aluno/treinos': typeof AlunoTreinosRoute
  '/aluno': typeof AlunoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/avaliacoes': typeof AlunoAvaliacoesRoute
  '/aluno/avatar': typeof AlunoAvatarRoute
  '/aluno/coach': typeof AlunoCoachRoute
  '/aluno/evolucao': typeof AlunoEvolucaoRoute
  '/aluno/financeiro': typeof AlunoFinanceiroRoute
  '/aluno/fotos': typeof AlunoFotosRoute
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/mensagens': typeof AlunoMensagensRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/timeline': typeof AlunoTimelineRoute
  '/aluno/treinos': typeof AlunoTreinosRoute
  '/aluno/': typeof AlunoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/aluno/agenda'
    | '/aluno/avaliacoes'
    | '/aluno/avatar'
    | '/aluno/coach'
    | '/aluno/evolucao'
    | '/aluno/financeiro'
    | '/aluno/fotos'
    | '/aluno/materiais'
    | '/aluno/mensagens'
    | '/aluno/perfil'
    | '/aluno/timeline'
    | '/aluno/treinos'
    | '/aluno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno/agenda'
    | '/aluno/avaliacoes'
    | '/aluno/avatar'
    | '/aluno/coach'
    | '/aluno/evolucao'
    | '/aluno/financeiro'
    | '/aluno/fotos'
    | '/aluno/materiais'
    | '/aluno/mensagens'
    | '/aluno/perfil'
    | '/aluno/timeline'
    | '/aluno/treinos'
    | '/aluno'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/aluno/agenda'
    | '/aluno/avaliacoes'
    | '/aluno/avatar'
    | '/aluno/coach'
    | '/aluno/evolucao'
    | '/aluno/financeiro'
    | '/aluno/fotos'
    | '/aluno/materiais'
    | '/aluno/mensagens'
    | '/aluno/perfil'
    | '/aluno/timeline'
    | '/aluno/treinos'
    | '/aluno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/agenda': {
      id: '/aluno/agenda'
      path: '/agenda'
      fullPath: '/aluno/agenda'
      preLoaderRoute: typeof AlunoAgendaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/avaliacoes': {
      id: '/aluno/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/aluno/avaliacoes'
      preLoaderRoute: typeof AlunoAvaliacoesRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/avatar': {
      id: '/aluno/avatar'
      path: '/avatar'
      fullPath: '/aluno/avatar'
      preLoaderRoute: typeof AlunoAvatarRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/coach': {
      id: '/aluno/coach'
      path: '/coach'
      fullPath: '/aluno/coach'
      preLoaderRoute: typeof AlunoCoachRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/evolucao': {
      id: '/aluno/evolucao'
      path: '/evolucao'
      fullPath: '/aluno/evolucao'
      preLoaderRoute: typeof AlunoEvolucaoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/financeiro': {
      id: '/aluno/financeiro'
      path: '/financeiro'
      fullPath: '/aluno/financeiro'
      preLoaderRoute: typeof AlunoFinanceiroRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/fotos': {
      id: '/aluno/fotos'
      path: '/fotos'
      fullPath: '/aluno/fotos'
      preLoaderRoute: typeof AlunoFotosRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/materiais': {
      id: '/aluno/materiais'
      path: '/materiais'
      fullPath: '/aluno/materiais'
      preLoaderRoute: typeof AlunoMateriaisRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/mensagens': {
      id: '/aluno/mensagens'
      path: '/mensagens'
      fullPath: '/aluno/mensagens'
      preLoaderRoute: typeof AlunoMensagensRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/timeline': {
      id: '/aluno/timeline'
      path: '/timeline'
      fullPath: '/aluno/timeline'
      preLoaderRoute: typeof AlunoTimelineRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/treinos': {
      id: '/aluno/treinos'
      path: '/treinos'
      fullPath: '/aluno/treinos'
      preLoaderRoute: typeof AlunoTreinosRouteImport
      parentRoute: typeof AlunoRoute
    }
  }
}

interface AlunoRouteChildren {
  AlunoAgendaRoute: typeof AlunoAgendaRoute
  AlunoAvaliacoesRoute: typeof AlunoAvaliacoesRoute
  AlunoAvatarRoute: typeof AlunoAvatarRoute
  AlunoCoachRoute: typeof AlunoCoachRoute
  AlunoEvolucaoRoute: typeof AlunoEvolucaoRoute
  AlunoFinanceiroRoute: typeof AlunoFinanceiroRoute
  AlunoFotosRoute: typeof AlunoFotosRoute
  AlunoMateriaisRoute: typeof AlunoMateriaisRoute
  AlunoMensagensRoute: typeof AlunoMensagensRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  AlunoTimelineRoute: typeof AlunoTimelineRoute
  AlunoTreinosRoute: typeof AlunoTreinosRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoAgendaRoute: AlunoAgendaRoute,
  AlunoAvaliacoesRoute: AlunoAvaliacoesRoute,
  AlunoAvatarRoute: AlunoAvatarRoute,
  AlunoCoachRoute: AlunoCoachRoute,
  AlunoEvolucaoRoute: AlunoEvolucaoRoute,
  AlunoFinanceiroRoute: AlunoFinanceiroRoute,
  AlunoFotosRoute: AlunoFotosRoute,
  AlunoMateriaisRoute: AlunoMateriaisRoute,
  AlunoMensagensRoute: AlunoMensagensRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  AlunoTimelineRoute: AlunoTimelineRoute,
  AlunoTreinosRoute: AlunoTreinosRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
